/*** Compiler Front-End Test automatically generated by the BNF Converter ***/
/*                                                                          */
/* This test will parse a file, print the abstract syntax tree, and then    */
/* pretty-print the result.                                                 */
/*                                                                          */
/****************************************************************************/
#include <iostream>
#include "Parser.H"
#include "Printer.H"
#include "Absyn.H"
#include "CodeGen.H"

int main(int argc, char ** argv)
{
  FILE *input;
  if (argc > 1)
  {
    input = fopen(argv[1], "r");
    if (!input)
    {
      fprintf(stderr, "Error opening input file.\n");
      exit(1);
    }
  }
  else input = stdin;
  /* The default entry point is used. For other options see Parser.H */
  Program* parse_tree = pProgram(input);
  if (parse_tree)
  {
	CodeGen* cg = new CodeGen();
	cg->codegen(parse_tree);

	printf("OK");
    return 0;
  }
  return 1;
}
