/*** Compiler Front-End Test automatically generated by the BNF Converter ***/
/*                                                                          */
/* This test will parse a file, print the abstract syntax tree, and then    */
/* pretty-print the result.                                                 */
/*                                                                          */
/****************************************************************************/
#include <iostream>
#include "Parser.H"
#include "Printer.H"
#include "Absyn.H"
#include "TypeChecker.H"
#include "TypeException.H"
#include "CodeGen.H"

int main(int argc, char ** argv)
{
  FILE *input;
  if (argc > 1)
  {
    input = fopen(argv[1], "r");
    if (!input)
    {
      fprintf(stderr, "Error opening input file.\n");
      exit(1);
    }
  }
  else input = stdin;
  /* The default entry point is used. For other options see Parser.H */
  Program* parse_tree = pProgram(input);
  if (parse_tree)
  {
    try {

      TypeChecker* tc = new TypeChecker();
      Codegen* cg = new Codegen();
      tc->typecheck(parse_tree);
      printf("TypeCheck OK");

      auto iR = cg->codegen(parse_tree);
      iR->dump()

      } catch (TypeException* e) {
          printf("TYPE ERROR");
          std::cout<< e->what();
          cout<< endl;
          return 1;
      }

    return 0;
  }
  return 1;
}


